# Generated by Django 5.0.6 on 2024-10-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='/profile_pictures/default_profile_picture.jpeg', upload_to='profile_pictures'),
        ),
    ]
