# Generated by Django 5.0.6 on 2024-09-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
