# Generated by Django 5.0.6 on 2024-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='occasion_object',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_object',
        ),
        migrations.AddField(
            model_name='product',
            name='occasion_object',
            field=models.ManyToManyField(to='myfancy.occasion'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_object',
            field=models.ManyToManyField(to='myfancy.type'),
        ),
    ]
