# Generated by Django 5.0.6 on 2024-10-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfancy', '0002_orders_is_canceled_alter_userprofile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
