# Generated by Django 5.0.6 on 2024-09-14 08:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfancy', '0004_address_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('product_object', 'user_object')},
        ),
    ]
