# Generated by Django 5.0.6 on 2024-09-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfancy', '0009_alter_product_occasion_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='occasion_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfancy.occasion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfancy.type'),
        ),
    ]
