# Generated by Django 5.0.6 on 2024-09-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfancy', '0012_alter_product_occasion_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('online_payment', 'Online Payment')], default='online_payment', max_length=200),
        ),
    ]
